{% set name = "dbstep" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0cb00250d8b91511d780dbe560c3565e6d2f097604d35dce90fdf3dbbc89f221

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cclib
    - numba
    - numpy
    - python >=3.6
    - scipy >=1.6

test:
  imports:
    - dbstep
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/patonlab/DBSTEP
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'DFT Based Steric Parameters'

extra:
  recipe-maintainers:
    - luchini18
